/**
 * Cloudflare Worker for quest-xr-glass-demo
 *
 * Gates the taxi analytics feature behind a secret key.
 * - Validates key via query param (?key=...), sets HttpOnly cookie
 * - Strips taxi UI elements from HTML when not authenticated
 * - Returns 403 for direct taxi room asset access when not authenticated
 */

const COOKIE_NAME = "taxi_auth";
const COOKIE_MAX_AGE = 86400 * 7; // 7 days

/**
 * Constant-time string comparison to prevent timing attacks
 */
function timingSafeEqual(a, b) {
  if (typeof a !== "string" || typeof b !== "string") return false;
  if (a.length !== b.length) {
    // Still do some work to avoid length-based timing
    let dummy = 0;
    for (let i = 0; i < b.length; i++) dummy |= b.charCodeAt(i);
    return false;
  }
  let result = 0;
  for (let i = 0; i < a.length; i++) {
    result |= a.charCodeAt(i) ^ b.charCodeAt(i);
  }
  return result === 0;
}

/**
 * Generate a simple HMAC-like signature for the cookie
 */
async function signCookie(timestamp, secret) {
  const encoder = new TextEncoder();
  const key = await crypto.subtle.importKey(
    "raw",
    encoder.encode(secret),
    { name: "HMAC", hash: "SHA-256" },
    false,
    ["sign"]
  );
  const signature = await crypto.subtle.sign(
    "HMAC",
    key,
    encoder.encode(String(timestamp))
  );
  return btoa(String.fromCharCode(...new Uint8Array(signature)));
}

/**
 * Verify the cookie signature
 */
async function verifyCookie(cookieValue, secret) {
  if (!cookieValue || !secret) return false;
  const parts = cookieValue.split(".");
  if (parts.length !== 2) return false;
  const [timestamp, signature] = parts;
  const ts = parseInt(timestamp, 10);
  if (isNaN(ts)) return false;
  // Check expiration (7 days)
  if (Date.now() - ts > COOKIE_MAX_AGE * 1000) return false;
  const expected = await signCookie(timestamp, secret);
  return timingSafeEqual(signature, expected);
}

/**
 * Create a signed cookie value
 */
async function createCookieValue(secret) {
  const timestamp = Date.now();
  const signature = await signCookie(timestamp, secret);
  return `${timestamp}.${signature}`;
}

/**
 * Parse cookies from request
 */
function parseCookies(request) {
  const cookieHeader = request.headers.get("Cookie") || "";
  const cookies = {};
  for (const pair of cookieHeader.split(";")) {
    const [key, ...rest] = pair.trim().split("=");
    if (key) cookies[key] = rest.join("=");
  }
  return cookies;
}

/**
 * HTMLRewriter handler to remove taxi analytics elements
 */
class TaxiElementRemover {
  element(element) {
    element.remove();
  }
}

/**
 * HTMLRewriter handler to inject a script flag for taxi auth status
 */
class TaxiAuthFlagInjector {
  constructor(isAllowed) {
    this.isAllowed = isAllowed;
  }

  element(element) {
    const flag = this.isAllowed ? "true" : "false";
    element.prepend(
      `<script>window.__TAXI_ALLOWED__=${flag};</script>`,
      { html: true }
    );
  }
}

/**
 * Check if request path is for taxi analytics room assets
 */
function isTaxiRoomPath(pathname) {
  // Currently the taxi room is part of the main app, but if there were
  // dedicated routes/assets, we'd block them here.
  // For now, we only gate access at the HTML/JS level.
  return false;
}

/**
 * Generic same-origin LLM relay: POST /api/llm
 * - Requires a valid taxi cookie
 * - Upstream URL comes from the X-LLM-Endpoint header (settings endpoint),
 *   normalized to end with /chat/completions
 * - API key comes only from the browser's Authorization header
 * - Blocks non-https, self host / workers.dev, localhost, IP literals
 */
const LLM_RELAY_PATH = "/api/llm";
const LLM_MAX_BODY_BYTES = 1024 * 1024; // default for any endpoint
// v22: voice transcription records up to 30 s: 16 kHz 16-bit mono WAV = 960,044 B -> base64 1,280,060 B
// + JSON. Only the opencode.ai upstream gets the larger limit (2 MB, ~46 s of audio).
const LLM_MAX_BODY_BYTES_OPENCODE = 2 * 1024 * 1024;
function llmBodyLimitFor(url) {
  try {
    const host = new URL(url).hostname.toLowerCase();
    if (host === "opencode.ai" || host.endsWith(".opencode.ai")) return LLM_MAX_BODY_BYTES_OPENCODE;
  } catch (e) { /* fall through */ }
  return LLM_MAX_BODY_BYTES;
}
const LLM_TIMEOUT_MS = 60000;
const LLM_USER_AGENT = "quest-xr-taxi-assistant/1.0";

// Errors generated by the relay itself carry X-Taxi-Relay-Error so the client
// can tell them apart from upstream (LLM provider) errors with the same status.
function jsonResponse(status, obj) {
  return new Response(JSON.stringify(obj), {
    status,
    headers: {
      "Content-Type": "application/json; charset=utf-8",
      "Cache-Control": "no-store",
      "X-Taxi-Relay-Error": "1",
    },
  });
}

function resolveLlmEndpoint(raw, selfHost) {
  if (!raw) return { error: "Missing X-LLM-Endpoint header" };
  let u;
  try {
    u = new URL(String(raw).trim());
  } catch (e) {
    return { error: "Invalid endpoint URL" };
  }
  if (u.protocol !== "https:") return { error: "Endpoint must use https://" };
  if (u.username || u.password) return { error: "Credentials in endpoint URL are not allowed" };
  if (u.port && u.port !== "443") return { error: "Non-standard ports are not allowed" };
  const host = u.hostname.toLowerCase().replace(/\.$/, "");
  if (
    host === selfHost ||
    host.endsWith(".workers.dev") || host === "workers.dev" ||
    host === "localhost" || host.endsWith(".localhost") ||
    /^\d{1,3}(\.\d{1,3}){3}$/.test(host) || host.includes(":") || host.startsWith("[") ||
    !host.includes(".")
  ) {
    return { error: "Endpoint host not allowed" };
  }
  u.hash = "";
  u.pathname = u.pathname.replace(/\/+$/, "");
  if (!u.pathname.endsWith("/chat/completions")) u.pathname += "/chat/completions";
  return { url: u.toString() };
}

async function handleLlmRelay(request, env, taxiAllowed, selfHost) {
  if (request.method !== "POST") {
    return new Response("Method Not Allowed", { status: 405, headers: { Allow: "POST" } });
  }
  if (!taxiAllowed) return jsonResponse(401, { error: { message: "Unauthorized" } });

  const resolved = resolveLlmEndpoint(request.headers.get("X-LLM-Endpoint"), selfHost);
  if (resolved.error) return jsonResponse(400, { error: { message: resolved.error } });

  const m = /^Bearer\s+(.+)$/i.exec(request.headers.get("Authorization") || "");
  const apiKey = m ? m[1].trim() : "";
  if (!apiKey) {
    return jsonResponse(400, { error: { message: "Missing API key: set it in the settings (Authorization: Bearer <key>)" } });
  }

  const bodyLimit = llmBodyLimitFor(resolved.url);
  const declared = parseInt(request.headers.get("Content-Length") || "0", 10);
  if (declared > bodyLimit) return jsonResponse(413, { error: { message: "Payload too large" } });
  const body = await request.arrayBuffer();
  if (body.byteLength > bodyLimit) return jsonResponse(413, { error: { message: "Payload too large" } });
  if (body.byteLength === 0) return jsonResponse(400, { error: { message: "Empty body" } });

  const session = (request.headers.get("X-Opencode-Session") || "").slice(0, 128) || crypto.randomUUID();

  let upstreamRes;
  try {
    upstreamRes = await fetch(resolved.url, {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
        "User-Agent": LLM_USER_AGENT,
        "x-opencode-session": session,
      },
      body,
      redirect: "manual",
      signal: AbortSignal.timeout(LLM_TIMEOUT_MS),
    });
  } catch (e) {
    const timeout = e && (e.name === "TimeoutError" || e.name === "AbortError");
    return jsonResponse(timeout ? 504 : 502, { error: { message: timeout ? "Upstream timeout" : "Upstream fetch failed" } });
  }

  return new Response(upstreamRes.body, {
    status: upstreamRes.status,
    headers: {
      "Content-Type": upstreamRes.headers.get("Content-Type") || "application/json",
      "Cache-Control": "no-store",
    },
  });
}

/**
 * Main request handler
 */
export default {
  async fetch(request, env, ctx) {
    const url = new URL(request.url);
    const pathname = url.pathname;
    const secret = env.TAXI_APP_KEY;

    // Handle logout
    if (url.searchParams.get("key") === "logout" || pathname === "/logout") {
      const redirectUrl = new URL(url);
      redirectUrl.searchParams.delete("key");
      if (pathname === "/logout") {
        redirectUrl.pathname = "/quest-mr/";
      }
      return new Response(null, {
        status: 302,
        headers: {
          Location: redirectUrl.toString(),
          "Set-Cookie": `${COOKIE_NAME}=; Path=/; Max-Age=0; HttpOnly; Secure; SameSite=Strict`,
        },
      });
    }

    // Handle key in query param
    const keyParam = url.searchParams.get("key");
    if (keyParam && secret) {
      if (timingSafeEqual(keyParam, secret)) {
        // Valid key - set cookie and redirect without key in URL
        const cookieValue = await createCookieValue(secret);
        const redirectUrl = new URL(url);
        redirectUrl.searchParams.delete("key");
        return new Response(null, {
          status: 302,
          headers: {
            Location: redirectUrl.toString(),
            "Set-Cookie": `${COOKIE_NAME}=${cookieValue}; Path=/; Max-Age=${COOKIE_MAX_AGE}; HttpOnly; Secure; SameSite=Strict`,
          },
        });
      }
      // Invalid key - redirect without the key param (don't reveal it's wrong via different behavior)
      const redirectUrl = new URL(url);
      redirectUrl.searchParams.delete("key");
      return new Response(null, {
        status: 302,
        headers: { Location: redirectUrl.toString() },
      });
    }

    // Check existing cookie
    const cookies = parseCookies(request);
    const isAuthenticated = secret
      ? await verifyCookie(cookies[COOKIE_NAME], secret)
      : false;

    // If no secret is configured, taxi features are disabled entirely
    const taxiAllowed = isAuthenticated && !!secret;

    // Same-origin LLM relay (requires taxi cookie)
    if (pathname === LLM_RELAY_PATH) {
      return handleLlmRelay(request, env, taxiAllowed, url.hostname.toLowerCase());
    }

    // Block direct access to taxi room assets if not authenticated
    if (isTaxiRoomPath(pathname) && !taxiAllowed) {
      return new Response("Forbidden", { status: 403 });
    }

    // Fetch the asset from static assets
    const response = await env.ASSETS.fetch(request);

    // Only transform HTML responses
    const contentType = response.headers.get("Content-Type") || "";
    if (!contentType.includes("text/html")) {
      return response;
    }

    // Apply HTMLRewriter to strip/inject taxi elements based on auth
    let rewriter = new HTMLRewriter().on("head", new TaxiAuthFlagInjector(taxiAllowed));

    if (!taxiAllowed) {
      // Remove taxi button and related elements
      rewriter = rewriter
        .on("#taxiAnalyticsButton", new TaxiElementRemover())
        .on("#taxiChatPanel", new TaxiElementRemover())
        .on("#taxiSettingsModal", new TaxiElementRemover());
    }

    return rewriter.transform(response);
  },
};
